[versions]
assertj = "3.23.1"
junit = "5.9.1"
mockito = "4.9.0"

[libraries]
assertj = { module = "org.assertj:assertj-core", version.ref = "assertj" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-vintage = { module = "org.junit.vintage:junit-vintage-engine", version.ref = "junit" }
mockito-inline = { module = "org.mockito:mockito-inline", version.ref = "mockito" }
mockito-junit = { module = "org.mockito:mockito-junit-jupiter", version.ref = "mockito" }

[bundles]
junit = [
  "junit-jupiter",
  "junit-vintage"
]
mockito = [
  "mockito-inline",
  "mockito-junit"
]